### ISSUE TITLE
Unit tests should not depend on external API

### ISSUE THREAD

**Issue by halfak** [wiki-ai/wb-vandalism#2]
Currently the unit tests for features depend on calls to wikidata.org.  We should change these so that we hard-code datasources in a call to revscoring's `solve()`.  We should independently test the datasources.  It is also probably a good idea to have an integration tests as part of our CI.  That could use an external API.

**Comment by Ladsgroup** [comment]
Moved to https://phabricator.wikimedia.org/T117274
